### ISSUE TITLE
Build errors with Meeting SDK v5.17.10.3562

### ISSUE THREAD

**Issue by badund** [zoom/meetingsdk-headless-linux-sample#12]
Is this a known issue? Previous versions of the SDK seem to work though

Attaching to zoomsdk-build
zoomsdk-build  | [ 10%] Building CXX object CMakeFiles/zoomsdk.dir/src/main.cpp.o
zoomsdk-build  | [ 20%] Building CXX object CMakeFiles/zoomsdk.dir/src/Zoom.cpp.o
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/src/Zoom.cpp: In lambda function:
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:45:63: error: invalid new-expression of abstract class type 'MeetingReminderEvent'
zoomsdk-build  |    45 |         reminderController->SetEvent(new MeetingReminderEvent());
zoomsdk-build  |       |                                                               ^
zoomsdk-build  | In file included from /tmp/meeting-sdk-linux-sample/src/Zoom.h:25,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:1:
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/src/events/MeetingReminderEvent.h:12:7: note:   because the following virtual functions are pure within 'MeetingReminderEvent':
zoomsdk-build  |    12 | class MeetingReminderEvent : public IMeetingReminderEvent
zoomsdk-build  |       |       ^~~~~~~~~~~~~~~~~~~~
zoomsdk-build  | In file included from /tmp/meeting-sdk-linux-sample/src/events/MeetingReminderEvent.h:7,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.h:25,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:1:
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/lib/zoomsdk/h/meeting_service_components/meeting_reminder_ctrl_interface.h:130:22: note:     'virtual void ZOOMSDK::IMeetingReminderEvent::onEnableReminderNotify(ZOOMSDK::IMeetingReminderContent*, ZOOMSDK::IMeetingEnableReminderHandler*)'
zoomsdk-build  |   130 |         virtual void onEnableReminderNotify(IMeetingReminderContent* content, IMeetingEnableReminderHandler* handle) = 0;
zoomsdk-build  |       |                      ^~~~~~~~~~~~~~~~~~~~~~
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:58:92: error: invalid new-expression of abstract class type 'MeetingRecordingCtrlEvent'
zoomsdk-build  |    58 |             auto recordingEvent = new MeetingRecordingCtrlEvent(onRecordingPrivilegeChanged);
zoomsdk-build  |       |                                                                                            ^
zoomsdk-build  | In file included from /tmp/meeting-sdk-linux-sample/src/Zoom.h:26,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:1:
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/src/events/MeetingRecordingCtrlEvent.h:12:7: note:   because the following virtual functions are pure within 'MeetingRecordingCtrlEvent':
zoomsdk-build  |    12 | class MeetingRecordingCtrlEvent : public IMeetingRecordingCtrlEvent {
zoomsdk-build  |       |       ^~~~~~~~~~~~~~~~~~~~~~~~~
zoomsdk-build  | In file included from /tmp/meeting-sdk-linux-sample/lib/zoomsdk/h/meeting_service_components/meeting_participants_ctrl_interface.h:9,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.h:20,
zoomsdk-build  |                  from /tmp/meeting-sdk-linux-sample/src/Zoom.cpp:1:
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/lib/zoomsdk/h/meeting_service_components/meeting_recording_interface.h:129:22: note:     'virtual void ZOOMSDK::IMeetingRecordingCtrlEvent::onRequestCloudRecordingResponse(ZOOMSDK::RequestStartCloudRecordingStatus)'
zoomsdk-build  |   129 |         virtual void onRequestCloudRecordingResponse(RequestStartCloudRecordingStatus status) = 0;
zoomsdk-build  |       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zoomsdk-build  | /tmp/meeting-sdk-linux-sample/lib/zoomsdk/h/meeting_service_components/meeting_recording_interface.h:137:22: note:     'virtual void ZOOMSDK::IMeetingRecordingCtrlEvent::onStartCloudRecordingRequested(ZOOMSDK::IRequestStartCloudRecordingHandler*)'
zoomsdk-build  |   137 |         virtual void onStartCloudRecordingRequested(IRequestStartCloudRecordingHandler* handler) = 0;
zoomsdk-build  |       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zoomsdk-build  | gmake[2]: *** [CMakeFiles/zoomsdk.dir/build.make:90: CMakeFiles/zoomsdk.dir/src/Zoom.cpp.o] Error 1
zoomsdk-build  | gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/zoomsdk.dir/all] Error 2
zoomsdk-build  | gmake: *** [Makefile:91: all] Error 2
zoomsdk-build exited with code 2

**Comment by analog88** [comment]
Hey @badund, if you're dealing with build errors while integrating the Zoom Meeting SDK, you might want to check out the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=build_errors_with_meeting_sdk&utm_content=Recall.ai_API).

It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video/metadata from meetings without you needing to spend months to build, scale and maintain these bots.

Here are the API docs: https://docs.recall.ai/page/tutorials

**Comment by badund** [comment]
Actually I'm not having any build errors. 

Nice try using Zoom's Github repo to market your expensive product nobody is buying. FYI, you profile has been flagged.

**Comment by Laksii-fr** [comment]
> Actually I'm not having any build errors.
> 
> Nice try using Zoom's Github repo to market your expensive product nobody is buying. FYI, you profile has been flagged.

did you find the solution?
