### ISSUE TITLE
failed to subscribe to raw audio with status 32

### ISSUE THREAD

**Issue by BakingBrains** [zoom/meetingsdk-headless-linux-sample#14]
Unable to get raw audio when joined to the meeting. Any suggestion or resolution. (Using latest zoom SDK)

![image](https://github.com/zoom/meetingsdk-headless-linux-sample/assets/51019420/8888db3d-7d92-4dc4-9dac-fe0ee66eb8fd)

**Comment by aheruz** [comment]
same here!

**Comment by aheruz** [comment]
@mgraczyk Did a fork with a work around
https://github.com/Quilt-AI/zoom-client

**Comment by mgraczyk** [comment]
Yeah you need to set `isAudioOff` to `false` in src/Zoom.cpp:146 like this:
```
    if (m_config.useRawAudio()) {
        param.isAudioOff = false;
        auto* audioSettings = m_settingService->GetAudioSettings();
        if (!audioSettings) return SDKERR_INTERNAL_ERROR;

        audioSettings->EnableAutoJoinAudio(true);
        audioSettings->EnableAlwaysMuteMicWhenJoinVoip(true);
        audioSettings->SetSuppressBackgroundNoiseLevel(Suppress_BGNoise_Level_None);

    }
 ```
 
 Unfortunately I need to make my fork private

**Comment by BakingBrains** [comment]
Thank you @mgraczyk @aheruz It worked.
