### ISSUE TITLE
stopping container once the meeting ends

### ISSUE THREAD

**Issue by NandyRL** [zoom/meetingsdk-headless-linux-sample#6]
I was wondering what was the use of running the container eternally, so I thought if there was a way to stop container when the meeting ends

**Comment by yuminglong318** [comment]
How did you stop the container once the meeting ends?

**Comment by tamagoeggo** [comment]
@NandyRL @yuminglong318, if you're trying to build a meeting bot check out the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=stopping_container_once_the_meeting_ends&utm_content=Recall.ai_API) for your meeting bots instead.

It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video from meetings without you needing to spend months to build, scale and maintain these bots.

Here are the API docs: https://docs.recall.ai/page/tutorials
