### ISSUE TITLE
client-id required

### ISSUE THREAD

**Issue by yuminglong318** [zoom/meetingsdk-headless-linux-sample#7]
client-id required error even i have config.ini configured

**Comment by NandyRL** [comment]
exec ./"$BUILD"/zoomsdk  --config config.ini; 

put this command in the run() in entry.sh

**Comment by yuminglong318** [comment]
yes, it works!
thanks!

**Comment by yuminglong318** [comment]
yes, it works!
thanks!

**Comment by NandyRL** [comment]
hey, can you get video recording ??

**Comment by yuminglong318** [comment]
no, I can not.

**Comment by tamagoeggo** [comment]
@NandyRL @yuminglong318, if you're trying to build a meeting bot check out the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=client_id_required&utm_content=Recall.ai_API) for your meeting bots instead.

It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video from meetings without you needing to spend months to build, scale and maintain these bots.

Here are the API docs: https://docs.recall.ai/page/tutorials
